spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost:3306}/${DB_NAME:auth_db}
    username: ${DB_USERNAME:user}
    password: ${DB_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8080

jwt:
  secret: T94@ek!X7%v2m#FqW&jzGp1Ls^B8ZtEo
  expiration: 3600000
